"use client"
import { useState, useEffect, useRef } from "react"
import { useReactToPrint } from "react-to-print"
import { saveNote } from "./actions"
import Link from "next/link"

export default function NotesEditor({ initialContent }: { initialContent: string }) {
  const [content, setContent] = useState(initialContent)
  const [saving, setSaving] = useState(false)
  const [lastSaved, setLastSaved] = useState<Date | null>(null)
  const printRef = useRef<HTMLDivElement>(null)

  const handlePrint = useReactToPrint({
    contentRef: printRef,
    documentTitle: "My Notes",
  })

  // Autosave logic
  useEffect(() => {
    // Don't save on initial mount
    if (content === initialContent) return

    const delayDebounceFn = setTimeout(async () => {
      setSaving(true)
      try {
        await saveNote(content)
        setLastSaved(new Date())
      } catch (error) {
        console.error("Failed to save:", error)
      } finally {
        setSaving(false)
      }
    }, 1500) // 1.5 second debounce

    return () => clearTimeout(delayDebounceFn)
  }, [content, initialContent])

  return (
    <div className="min-h-screen bg-gray-50 py-8">
      <div className="max-w-4xl mx-auto px-4">
        <div className="flex justify-between items-center mb-6">
          <div className="flex items-center gap-4">
            <Link href="/apps/dashboard" className="text-blue-600 hover:underline flex items-center gap-1">
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
              </svg>
              Dashboard
            </Link>
            <h1 className="text-2xl font-bold text-gray-900">Notes App</h1>
          </div>
          <div className="flex items-center gap-4">
            <span className="text-sm text-gray-500 italic">
              {saving ? "Saving..." : lastSaved ? `Last saved ${lastSaved.toLocaleTimeString()}` : "Ready"}
            </span>
            <button
              onClick={() => handlePrint()}
              className="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg font-medium transition-colors shadow-sm"
            >
              Export PDF / Print
            </button>
          </div>
        </div>
        
        <div className="bg-white rounded-xl shadow-md border border-gray-200 overflow-hidden">
          <textarea
            value={content}
            onChange={(e) => setContent(e.target.value)}
            placeholder="Start typing your note here... it will autosave as you type."
            className="w-full h-[70vh] p-10 focus:outline-none resize-none text-gray-800 leading-relaxed text-lg"
          />
        </div>

        {/* Hidden area for printing to ensure better formatting */}
        <div className="hidden">
          <div ref={printRef} className="p-12 text-gray-900 bg-white">
            <h1 className="text-3xl font-bold mb-8 border-b pb-4">My Notes</h1>
            <div className="whitespace-pre-wrap leading-relaxed text-lg">
              {content}
            </div>
            <div className="mt-12 pt-4 border-t text-xs text-gray-400">
              Generated by App Portal - {new Date().toLocaleDateString()}
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
